"""Silent Signal hand-motion API.

Run from this directory:
    python -m uvicorn api:app --host 0.0.0.0 --port 8001

The keypad trigger and video analysis are deliberately separate. A backend can
first notify this API that a keypad was pressed, then upload the video recorded
by the Raspberry Pi to ``/analyze/silent-signal`` when it is available.
"""

from __future__ import annotations

from collections import deque
from datetime import datetime, timezone
from pathlib import Path
import tempfile
from typing import Literal

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import JSONResponse
from pydantic import BaseModel, Field

from detector import analyze_video_for_silent_signal

app = FastAPI(title="Silent Signal Vision API")


class KeypadTriggerRequest(BaseModel):
    """Payload sent by the backend after a valid keypad event.

    Do not include the actual keypad PIN in this payload. ``triggerId`` should
    be a unique ID generated by the backend and is reused when uploading video.
    """

    triggerId: str = Field(min_length=1, max_length=128)
    triggeredAt: datetime
    triggerType: Literal["KEYPAD"] = "KEYPAD"
    securityEventId: str | None = Field(default=None, max_length=128)
    deviceId: str | None = Field(default=None, max_length=128)


_recent_keypad_triggers: deque[dict] = deque(maxlen=100)


@app.get("/health")
def health() -> dict[str, str]:
    return {"status": "ok", "service": "silent-signal-vision"}


@app.post("/triggers/keypad", status_code=202)
def receive_keypad_trigger(payload: KeypadTriggerRequest) -> dict:
    """Accept and record a keypad trigger without requiring a camera."""

    trigger = payload.model_dump(mode="json")
    _recent_keypad_triggers.append(trigger)
    return {
        "status": "accepted",
        "trigger": trigger,
        "nextAction": "UPLOAD_VIDEO",
        "uploadEndpoint": "/analyze/silent-signal",
        "message": "Keypad trigger received. Upload the recorded MP4 using the same triggerId.",
    }


@app.get("/triggers/keypad/latest")
def latest_keypad_trigger() -> dict:
    """Return the most recent trigger; useful for LAN integration testing."""

    if not _recent_keypad_triggers:
        raise HTTPException(status_code=404, detail="No keypad trigger has been received.")
    return {"status": "ok", "trigger": _recent_keypad_triggers[-1]}


@app.post("/analyze/silent-signal")
async def analyze_silent_signal(
    file: UploadFile = File(...),
    triggerId: str = Form(...),
    triggerType: str = Form("KEYPAD"),
    securityEventId: str | None = Form(None),
    triggeredAt: str = Form(...),
):
    """Analyze an MP4 recorded after a keypad trigger."""

    if not file.filename or not file.filename.lower().endswith(".mp4"):
        return JSONResponse(
            status_code=415,
            content={
                "status": "error",
                "result": None,
                "message": "Only MP4 files are supported.",
                "code": "UNSUPPORTED_VIDEO_FORMAT",
            },
        )

    with tempfile.NamedTemporaryFile(suffix=".mp4", delete=False) as tmp:
        tmp.write(await file.read())
        tmp_path = Path(tmp.name)

    try:
        signal_result = analyze_video_for_silent_signal(tmp_path)
    except ValueError:
        return JSONResponse(
            status_code=422,
            content={
                "status": "error",
                "result": None,
                "message": "Unable to read video metadata.",
                "code": "INVALID_VIDEO_FILE",
            },
        )
    finally:
        tmp_path.unlink(missing_ok=True)
        await file.close()

    vision_events = []
    if signal_result.detected:
        vision_events.append(
            {
                "eventType": "SILENT_SIGNAL",
                "confidence": signal_result.confidence,
                "detectedFrame": signal_result.detected_frame,
                "details": {
                    "signalCode": signal_result.signal_code,
                    "signalName": signal_result.signal_name,
                },
            }
        )

    return JSONResponse(
        content={
            "status": "success",
            "result": {
                "trigger": {
                    "triggerId": triggerId,
                    "triggerType": triggerType,
                    "securityEventId": securityEventId,
                    "triggeredAt": triggeredAt,
                },
                "analyzedAt": datetime.now(timezone.utc).astimezone().isoformat(timespec="seconds"),
                "video": {
                    "fileName": file.filename,
                    "durationSeconds": None,
                    "fps": None,
                    "frameCount": signal_result.frames_analyzed,
                },
                "behavior": None,
                "visionEvents": vision_events,
                "observations": {
                    "trackedPersonCount": None,
                    "hasTracking": None,
                    "hasPose": signal_result.hand_present_frames > 0,
                },
            },
        }
    )
